name: blbiDeathDrop
version: '${project.version}'
main: com.blbilink.mc.death_drop.DeathDrop
api-version: '1.21'
description: A plugin for managing player death drops
author: blbilink 
folia-supported: true